-- Prérequis : exécuter 01_infrastructure.sql.
-- Administration des droits avec un utilisateur autorisé à utiliser SECURITYADMIN.
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;

-- SYSADMIN hérite de TRANSFORMER, jamais l'inverse.
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.STAGING TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.MARTS TO ROLE TRANSFORMER;

-- Les tables, vues, stages et formats seront créés avec TRANSFORMER
-- comme rôle principal afin qu'il en soit propriétaire.
SHOW GRANTS TO ROLE TRANSFORMER;
