USE ROLE TRANSFORMER;
USE WAREHOUSE NYC_TAXI_WH;
SELECT FILE_NAME, LAST_LOAD_TIME, ROW_COUNT, ROW_PARSED, STATUS, ERROR_COUNT
FROM TABLE(NYC_TAXI.INFORMATION_SCHEMA.COPY_HISTORY(
 TABLE_NAME => 'NYC_TAXI.RAW.YELLOW_TRIPDATA',
 START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP())))
ORDER BY LAST_LOAD_TIME;
