-- Exécuter avant et après le rejeu complet de février, sans autre run en cours.
-- Comparer les 18 volumes ; conserver les deux résultats comme preuve.
USE ROLE TRANSFORMER;
USE WAREHOUSE NYC_TAXI_WH;

SELECT 'RAW.YELLOW_TRIPDATA' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.RAW.YELLOW_TRIPDATA
UNION ALL
SELECT 'RAW.TAXI_ZONE_LOOKUP' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.RAW.TAXI_ZONE_LOOKUP
UNION ALL
SELECT 'STAGING.STG_TLC__YELLOW_TRIPS' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.STAGING.STG_TLC__YELLOW_TRIPS
UNION ALL
SELECT 'STAGING.STG_TLC__TAXI_ZONES' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.STAGING.STG_TLC__TAXI_ZONES
UNION ALL
SELECT 'STAGING.PAYMENT_TYPE_CODES' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.STAGING.PAYMENT_TYPE_CODES
UNION ALL
SELECT 'STAGING.RATE_CODE_CODES' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.STAGING.RATE_CODE_CODES
UNION ALL
SELECT 'STAGING.VENDOR_CODES' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.STAGING.VENDOR_CODES
UNION ALL
SELECT 'INTERMEDIATE.INT_TRIPS__FLAGGED' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.INTERMEDIATE.INT_TRIPS__FLAGGED
UNION ALL
SELECT 'INTERMEDIATE.INT_TRIPS__ENRICHED' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.INTERMEDIATE.INT_TRIPS__ENRICHED
UNION ALL
SELECT 'MARTS.DIM_DATE' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.DIM_DATE
UNION ALL
SELECT 'MARTS.DIM_ZONE' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.DIM_ZONE
UNION ALL
SELECT 'MARTS.DIM_VENDOR' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.DIM_VENDOR
UNION ALL
SELECT 'MARTS.DIM_PAYMENT_TYPE' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.DIM_PAYMENT_TYPE
UNION ALL
SELECT 'MARTS.DIM_RATE_CODE' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.DIM_RATE_CODE
UNION ALL
SELECT 'MARTS.FCT_TRIPS' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.FCT_TRIPS
UNION ALL
SELECT 'MARTS.MART_ZONE_HOURLY_DEMAND' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.MART_ZONE_HOURLY_DEMAND
UNION ALL
SELECT 'MARTS.MART_DAILY_REVENUE' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.MART_DAILY_REVENUE
UNION ALL
SELECT 'MARTS.MART_DATA_QUALITY' AS object_name, COUNT(*) AS row_count
FROM NYC_TAXI.MARTS.MART_DATA_QUALITY
ORDER BY object_name;
